commodity_list = [
    "Bottle gourd",
    "Snakeguard",
    "Ridgeguard(Tori)",
    "Potato",
    "Cucumbar(Kheera)",
    "Pumpkin",
    "Amaranthus",
    "Cauliflower",
    "Cowpea(Veg)",
    "Onion Green",
    "Capsicum",
    "Tapioca",
    "Brinjal",
    "Green Peas",
    "Grapes",
    "Carrot",
    "Cotton",
    "Ashgourd",
    "Banana",
    "Soanf",
    "Knool Khol",
    "Mustard",
    "Wheat",
    "Ginger(Green)",
    "Spinach",
    "Groundnut",
    "Cabbage",
    "Green Chilli",
    "Onion",
    "Banana - Green",
    "Coconut",
    "Beetroot",
    "Rice",
    "Paddy(Common)",
    "Mint(Pudina)",
]
